from flask import Flask, request, jsonify, send_from_directory, send_file
from flask_cors import CORS
import tensorflow as tf
import numpy as np
import os
from werkzeug.utils import secure_filename
from tensorflow.keras.preprocessing import image
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime

# ===============================
# App Setup
# ===============================
app = Flask(__name__)
CORS(app)

# ===============================
# Configuration
# ===============================
UPLOAD_FOLDER = "uploads"
MODEL_PATH = "model/keras_model.h5"
REPORT_FOLDER = "reports"

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(REPORT_FOLDER, exist_ok=True)

# ===============================
# Class Names
# ===============================
CLASS_NAMES = [
    "Oral Cancer",
    "Normal"
]

# ===============================
# Load Model
# ===============================
try:
    model = tf.keras.models.load_model(MODEL_PATH, compile=False)
    print("✅ Oral Cancer model loaded successfully")
except Exception as e:
    print("❌ Error loading model:", e)
    model = None

# ===============================
# Routes
# ===============================
@app.route("/", methods=["GET"])
def home():
    return jsonify({"message": "Oral Cancer Detection API is running"})

# ===============================
# Prediction Route
# ===============================
@app.route("/predict", methods=["POST"])
def predict():
    if model is None:
        return jsonify({"error": "Model not loaded"}), 500

    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files["file"]
    if file.filename == "":
        return jsonify({"error": "No file selected"}), 400

    filename = secure_filename(file.filename)
    filepath = os.path.join(app.config["UPLOAD_FOLDER"], filename)
    file.save(filepath)

    try:
        input_size = model.input_shape[1:3]

        img = image.load_img(filepath, target_size=input_size)
        img = image.img_to_array(img)
        img = (img / 127.5) - 1
        img = np.expand_dims(img, axis=0)

        preds = model.predict(img, verbose=0)[0]
        predicted_index = int(np.argmax(preds))
        confidence = float(preds[predicted_index])

        prediction = CLASS_NAMES[predicted_index]

        return jsonify({
            "prediction": prediction,
            "confidence": round(confidence * 100, 2),
            "image_name": filename
        })

    except Exception as e:
        print("❌ Prediction error:", e)
        return jsonify({"error": "Failed to process image"}), 500

# ===============================
# PDF REPORT GENERATION
# ===============================
@app.route("/generate-report", methods=["POST"])
def generate_report():
    data = request.json

    patient_name = data.get("patient_name", "Anonymous")
    prediction = data.get("prediction", "N/A")
    confidence = data.get("confidence", "N/A")
    image_name = data.get("image_name", "N/A")

    timestamp = datetime.now().strftime("%d %b %Y, %I:%M %p")
    report_path = os.path.join(REPORT_FOLDER, "Oral_Cancer_Report.pdf")

    c = canvas.Canvas(report_path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, height - 1.2 * inch, "Oral Cancer Detection Report")

    # Divider
    c.line(1 * inch, height - 1.5 * inch, width - 1 * inch, height - 1.5 * inch)

    # Content
    c.setFont("Helvetica", 12)
    y = height - 2.2 * inch

    c.drawString(1 * inch, y, f"Patient Name: {patient_name}")
    y -= 20
    c.drawString(1 * inch, y, f"Date & Time: {timestamp}")
    y -= 20
    c.drawString(1 * inch, y, f"Uploaded Image: {image_name}")
    y -= 30

    c.setFont("Helvetica-Bold", 13)
    c.drawString(1 * inch, y, "Prediction Result")
    y -= 20

    c.setFont("Helvetica", 12)
    c.drawString(1 * inch, y, f"Prediction: {prediction}")
    y -= 20
    c.drawString(1 * inch, y, f"Confidence: {confidence}%")
    y -= 40

    # Disclaimer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        1 * inch,
        y,
        "Disclaimer: This report is generated by an AI system for educational purposes only."
    )
    y -= 15
    c.drawString(
        1 * inch,
        y,
        "It is not a medical diagnosis. Please consult a qualified medical professional."
    )

    # Footer
    c.setFont("Helvetica", 9)
    c.drawCentredString(
        width / 2,
        0.75 * inch,
        "Oral Cancer Detection System | SRM Institute of Science and Technology"
    )

    c.save()

    return send_file(
        report_path,
        as_attachment=True,
        download_name="Oral_Cancer_Report.pdf"
    )

# ===============================
# Serve Uploaded Images
# ===============================
@app.route("/uploads/<filename>")
def uploaded_file(filename):
    return send_from_directory(app.config["UPLOAD_FOLDER"], filename)

# ===============================
# Run Server
# ===============================
if __name__ == "__main__":
    app.run(port=5000, debug=True)
